version: '3.8'

services:
  eureka-server:
    build:
      context: ./scripts/service-discovery-server/service-discovery-server
      dockerfile: Dockerfile
    restart: always
    environment:
      - spring.application.name=service-discovery-server
      - server.port=8761
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    ports:
      - "8761:8761"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"] 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  config-server:
    depends_on:
      eureka-server:
        condition: service_healthy
    build:
      context: ./scripts/config-server/config-server
      dockerfile: Dockerfile
    restart: always
    environment:
      - spring.application.name=config-server
      - server.port=8888
      - spring.cloud.config.server.git.uri=https://github.com/caoh29/OMS-config.git
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    ports:
      - "8888:8888"
    networks:
      - backend

networks:
  backend:
    driver: bridge
