version: '3.8'

services:
  config-server:
    build:
      context: ./scripts/config-server/config-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8888"
    networks:
      - backend

networks:
  backend:
    driver: bridge
